consul/consul.go, consul/consul_test.go, consul/consul_test_server.go, sync/sync.go
We should not use Consul agent "node name" as a resolvable hostname, but rather stick to its Address.
=> Hostname to Agent-address refactoring

sync/sync.go, sync/sync_bench_test.go
New | Loops | Speed [ns/op]
------------ | -------------|--------
BenchmarkDeregisterConsulServicesThatAreNotInMarathonApps10x2-4   |	  300000	|      4684
BenchmarkDeregisterConsulServicesThatAreNotInMarathonApps100x2-4  |	   30000	|     53626
BenchmarkDeregisterConsulServicesThatAreNotInMarathonApps100x100-4	|     300 |	   5359705
Old | Loops | Speed [ns/op]
------------ | -------------|--------
BenchmarkDeregisterConsulServicesThatAreNotInMarathonApps10x2-4   |	  200000	   |   6307
BenchmarkDeregisterConsulServicesThatAreNotInMarathonApps100x2-4  |	    2000	|    608956
BenchmarkDeregisterConsulServicesThatAreNotInMarathonApps100x100-4	 |      1 |	1460033471
Generated with `go test ./sync -bench=.`
=> Speed up consul services deregistration during sync

.travis.yml, apps/app.go, consul/consul.go, consul/consul_stub.go, consul/services.go, events/events.go, events/task_health_change.go, marathon/marathon.go, marathon/marathon_stub.go, sync/sync.go, sync/sync_bench_test.go, sync/sync_test.go, tasks/id.go, tasks/id_test.go, tasks/task.go, utils/apps.go, web/event_handler.go, web/event_handler_test.go
Currently our code is [Stringly Typed](http://c2.com/cgi/wiki?StringlyTyped). I added ID alias type for strings.
=> Create alias types for Id

README.md, config/config.go, main.go, marathon/marathon.go, marathon/marathon_stub.go, marathon/marathon_stub_test.go, marathon/marathon_test.go, sync/config.go, sync/sync.go, sync/sync_bench_test.go, sync/sync_test.go
Scheduled Marathon-Consul sync will run:
1. only when specified node has leadership
2. always when forced
=> Marathon leadership-aware sync

consul/consul.go, consul/consul_stub.go, consul/consul_stub_test.go, consul/consul_test.go, sync/sync_test.go, web/event_handler.go, web/event_handler_test.go
Fixes #21 
There are some gentle changes in the behaviour of event handlers, 
for example: we don't return 400 if there are no services registered in Consul etc (they could be removed by other events or it's just some marathon-noise). 
(sorry for the blank lines added :P :cookie: :cake: :cherries: )
=> Event-based deregistration fixed (now Consul-aware)

.goxc.json, README.md, config/config.go, config/config_test.go, debian/config.json, debian/marathon-consul.service
systemd doesn't forward output to file so I added config option to write logs to file.
=> Fixes #36 | Add systemd config

README.md, events/deployment_info.go, events/deployment_info_test.go, events/deployment_step_success_with_groups.json
=> Fixing deployment events handling for apps in groups

apps/app.go, consul/consul.go, consul/consul_test.go
=> Multiple checks, fix for url encoding, TCP/Command checks

apps/task.go, apps/task_test.go, sync/sync_test.go, utils/apps.go, web/event_handler.go, web/event_handler_test.go
This PR intorduce logic in killing stoped application. Only tasks from killed/stoped application will be deregistered.
This fixes #72 #35 #42
=> Fixes #72 | Unregister only tasks for given apps

web/event_handler.go, web/event_handler_test.go
Simpify task deregistration. Do not query marathon to check
if this app is managed by marathon-consul.
=> Unregister tasks (even for apps without label)

events/unhealthy_task_kill.go, events/unhealthy_task_kill_test.go, web/event_handler.go, web/event_handler_test.go
Marathon 1.1.1 introduced new event `unhealthy_task_kill_event`
that occurs when task is scheduled to kill after becomes unhealthy.
This change make marathon-consul aware of this event.
=> Fixes #83 | Unregister unhealthy killed tasks

.travis.yml, apps/app.go, consul/consul_test.go
I notice that `make build` fails because two field tags are invalid. 
```
apps/app.go:19: struct field tag `json:"value` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
exit status 1
consul/consul_test.go:537: struct field tag `json:"value` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
exit status 1
make: *** [test] Error 1
```
I fixed it and change CI to check whole project builds not only tests pass.
=> Fix wrong tag field

consul/consul.go, consul/consul_test.go, service/service_test.go, utils/errors.go, utils/errors_test.go, web/event_handler.go
Deregistering by task used to load all nodes (service instances) and loop over them in search for marathon task tag. With this change it loads all services and only loads nodes of services containing the marathon task tag.
It also correctly handles the corner case when there are multiple nodes containing the same marathon task id tag – it deregisters all of them. Before it would deregister only the first occurrence.
=> More efficient deregistering by task

consul/consul.go, consul/consul_stub.go, consul/consul_stub_test.go, consul/consul_test.go, service/service.go, sync/error_service_registry_stub_test.go, sync/sync_test.go, web/event_handler.go
Change base to develop after #104 gets merged.
=> Removes unnecessary argument to DeregisterByTask

Makefile, consul/consul_stub.go, metrics/metrics_test.go, sync/sync_test.go
Enable `-race` during tests and fix race conditions.
=> Enable race detector in tests

apps/app.go, apps/app.json, apps/app_test.go, consul/consul.go, consul/consul_test.go
If `port` is present in health check configuration then it's used instead of `portIndex`. This allows performing health check on static ports.
Change will apply only to newly started tasks, old won't be touched.
=> Fixes #108 Use static port number in health check

sync/sync.go, sync/sync_test.go
When doing sync and coming across a service without marathon-task tag we used to skip that service and leave it in the registry. This change causes the service to get deregistered, as sync's subsequent registering phase should reregister such service properly.
The service will be unavailable for a couple of seconds in this process – before its new healthchecks become passing. If that's a problem, it's advised to add marathon-task tag to all registered services before starting updated marathon-consul, e.g. using migration script from #106.
=> Reregistering on missing marathon-task tag during sync

.goxc.json
There is an [goxc issue](https://github.com/laher/goxc/issues/90) that
say there won't be workarounds for missing vendoring support in `go vet`
and `go test`. To support building with goxc with vendoring we need to
disable this two tasks.
Related to #101
=> Exclude `go-vet` and `go-test` from `goxc`

apps/app.go, apps/app_test.go, consul/consul_stub.go, sync/sync.go, sync/sync_test.go, utils/apps.go
In multi-registration scenario, some, but not all, service registrations may fail. Sync should check if all registrations are in Consul and register the missing ones.
Change base to *develop* once #114 is merged.
=> Sync support for multi-registrations

README.md, config/config.go, consul/config.go, consul/consul.go, consul/consul_test.go, debian/config.json
Introducing `consul-ignored-healthchecks` configuration property which allows one to ignore specified types of Marathon health checks during service registration in Consul.
Fixes #118
=> Blacklisted Healthcheck types

sync/sync.go, sync/sync_test.go
Explicitly handle a rare scenario during sync in which a task has more registrations than it should have according to its application configuration.
This may happen when application configuration is changed (now defining less registrations) and then the deployment this caused is rolled back – the new application configuration still stays in Marathon. Or we end up in some weird state. Since we don't know what to do in such scenario – we don't know which service to deregister – I suggest skipping such task with a log message.
We could also deregister all registrations and register the task again, but this seemed like a bad idea to me – the deployment with this new configuration was rolled back after all!
=> Skip tasks with excess registrations when syncing

sync/sync.go
Switching registering and deregistering places for smooth migration from 0.4.x to 1.0.0, without having to migrate using this script #106. We want to register services in the new format before removing the old entries to avoid unavailability. Shouldn't make a difference for the synchronization process. @janisz do you see any potential problem with that?
=> Register first, deregister second in sync process

README.md, apps/app.go, apps/app_test.go, utils/apps.go
Turns out portDefinitions.port field always gets populated with some port, even if you configure it as 0 (in which case it's random). We should always read ports from task configuration.
=> Ignoring portDefinitions.port field, always picking task ports

web/event_handler_test.go
In Go 1.8 json Marshaler/Unmarshaler gives more detailed errors and one of the tests depends on the exact error message.
I fixed the failing test - I'm not really sure if approach is right so I will leave it here to discuss it further
=> Fix tests on tip (golang 1.8)

.goxc.json, Makefile
goxc by default interpolate version. After swich to fpm and docker
we must manually add proper ldflag to make version set.
=> Fixes #135 | Version number interpolation

config/config.go, config/config_test.go, consul/agents.go, consul/config.go, consul/consul_test.go, consul/consul_test_server.go, debian/config.json, marathon/config.go, marathon/marathon.go, metrics/config.go, metrics/metrics.go, sync/config.go, sync/sync.go, sync/sync_test.go, time/time.go, time/time_test.go
Currently we allow user to specify intervals/timeouts in
human readable format only in command line flags. This commit
introduce allowign user to specify duration as inteager nanoseconds or
as formated string. String should have format supported by
time.ParseDuration.
=> Fixes #56 | Humman-readable interval in config

web/event_handler.go
Marathon with Mesos 0.28 has a TASK_KILLING event that will be emitted when the
task is about to get killed. This should be the earliest indicator that the
instance should be removed from consul.
=> Enable deregister on TASK_KILLING

Makefile, consul/consul_stub.go, consul/consul_stub_test.go, install_consul.sh, marathon/marathon_stub.go, time/time_test.go, web/event_handler.go, web/event_handler_test.go, web/web_handler.go, web/web_handler_test.go
In addition to adding nonblocking handling of events i added:
* `make format` and `make check` that runs same metalinter command as travis.ci
* bumped Consul version to 0.7.2 to fix random segfaults on Mac
* fixed race condition detected by `go test -race` in `MarathonerStub`
* fixed race condition in `even_hander_test` that caused tests to fail randomly (2nd commit)
Bit more about test fixes. I moved `web_handler` test suite to `web_handler_test` and it tests only `web_handler`, the event queue is stubbed. `event_handler` tests on the other hand no longer start `web_handler`, instead events that should be processed are sent directly to the event queue. This fixes a non-trivial race condition in tests, where success of test depended on wether request will be processed by `web_handler` and …
=> Nonblocking events

.gitignore, .travis.yml, Makefile
travis.ci configuration uses make commands to be able to replicate CI builds
on local machine
=> Move all build logic and dependencies installs to Makefile

events/task_health_change.go, events/task_health_change_test.go, web/event_handler.go
Marathon moved from tasks to instances to support pods.
We didn't want to add pods support right now but we need
to handle events that are not backward compatible. To do this
I introduced `TaskID()` that returns task id from instanceId if
task id was not present in event. This is shortcut just to enable
marathon-consul to be used with Marathon 1.4. We need to rethink
if/how we want to support pods and changed Marathon API.
Fixes: #148
=> Handle Task HealthChange without TaskID.

.travis.yml, install_consul.sh
Testing a possible fix for the curl issue.
=> Fix consul curl issue on Travis

consul/consul_test_server.go
Test are flaky due to small Consul client timeout. Fixed by increasing
client timeout.
=> Fixes flaky consul test.

consul/consul_test.go
nss-myhostname, libnss_myhostname.so.2 — Provide hostname resolution for the locally configured system hostname.
> The hostnames "localhost" and "localhost.localdomain" (as well as any hostname ending in ".localhost" or ".localhost.localdomain") are resolved to the IP addresses 127.0.0.1 and ::1.
https://www.freedesktop.org/software/systemd/man/nss-myhostname.html
=> FIX *.locahost is resolvable with nss-myhostname

metrics/metrics.go, metrics/metrics_test.go, sync/sync.go
Metrics will be cleared when instnace does not perform scheduled sync.
=> Fixes #184 | Clear metrics

apps/task.go, apps/task_test.go, marathon/marathon.go, marathon/marathon_stub.go, sync/error_marathon_stub_test.go, sync/sync.go, sync/sync_test.go, web/event_handler.go
Task is small object (112 bytes) mostly pointers (4 strings and 2 arrays).
There is no reason for using `[]*Tasks` in Marathon response.
Refs: https://github.com/allegro/marathon-consul/pull/190#discussion_r103429767
=> Replace `[]*Tasks` with `[]Tasks`

marathon/marathon.go, marathon/marathon_test.go
Hi, would you be open to adjusting the range of supported values of the marathon location parameter?
In order to join multiple marathons (e.g. per dev-team, per project) we are discovering their (semi-random) locations through linkerd (https://linkerd.io/documentation/).
This changes our --marathon-location value from the standard hostname:port into something like  --marathon-location=localhost:4141/ops-staging/marathon-devteam-1
Proposed fix checks, naively, for the existence of "path" and divides it into host  and url that is then prefixing the path param.
=> support for a path in marathon location

README.md, config/config.go, main.go, marathon/config.go, marathon/marathon.go, marathon/marathon_stub.go, marathon/marathon_stub_test.go, marathon/marathon_test.go, sse/sse.go, sync/error_marathon_stub_test.go, sync/sync.go, sync/sync_test.go
Mentioned: https://github.com/allegro/marathon-consul/pull/187#discussion_r103667851
=> Move sync.Leader to marathon module

marathon/marathon.go, marathon/marathon_test.go, marathon/streamer.go
Put HTTP authentication in Header instead of URL. This will prevent leaking credentials in logs when error is logged with authentication information.
=> Fixes #209 | Sanitize http logs

consul/consul.go, consul/consul_test.go, service/service.go
In some cases we want to add tags to services already registered in consul. This option allow external tools to add tags to existing services and order Consul to keep tags and propagate to cluster.
=> Enable tag override to allow extrnal tools adding tags

consul/consul_test.go
On OS X executing tests with request retry number set to 100 was taking too much time. Now it finishes in 25-60s which is acceptable.
=> Decrease request retry number to speed up tests

README.md
`sync-leader` was replaced with `marathon-leader` by #211.
This patch updates the readme to reflects this change.
Fixes: #217
=> Replace sync-leader with marathon-leader in readme

README.md, config/config.go, config/config_test.go, consul/config.go, consul/consul.go, consul/consul_test_server.go, debian/config.json
Add config option to configure to disable the anti-entropy feature
for services. See https://www.consul.io/docs/agent/services.html.
=> Make EnableTagOverride configurable

marathon/marathon.go
Error is returned so there is no need to log it. It should be done by caller.
=> Remove unnecessary logging.

Makefile, README.md
=> Describe how to release new version.

README.md, config/config.go, config/config_test.go, consul/agents.go, consul/agents_test.go, consul/config.go, consul/consul_test_server.go, debian/config.json
In some cases consul agents cache could be empty.
This chagne allow providing consul agent hostname to
initially populate the cache.
Fixes: #191
=> Allow to configure startup consul agent

README.md, config/config.go, marathon/marathon.go
This is useful if you always have only 1 instance running (think of `marathon-consul` as a marathon app ;) ) and marathon address is provided by consul DNS.
Do we missed something?
=> Disable Leader detection with a '*'

events/event_handler.go
Empty event type could be empty. This could happen when Marathon
is restarted. Current message was misleading.
=> Handle empty event type

apps/app.go, apps/app_bench_test.go, apps/app_test.go, consul/consul_test.go
This PR extracts commonTags outside of loop.
They are not changed inside the loop so there is no
need to recalculate them every time.
Ta reduce allocations tags slice i create with
initial capacity equal to the lenght of application labels.
```
benchmark                              old ns/op     new ns/op     delta
BenchmarkApp_RegistrationIntents-8     438           415           -5.25%
BenchmarkApp_RegistrationIntents-8     436           419           -3.90%
BenchmarkApp_RegistrationIntents-8     432           415           -3.94%
benchmark                              old allocs     new allocs     delta
BenchmarkApp_RegistrationIntents-8     4              3              -25.00%
BenchmarkApp_RegistrationIntents-8     4              3              -25.00% …
```
=> Calculate common tags only once.

main.go
After `sse.NewHandler` was moved to fucntion, `defer` was
called everytime handler was created not just before exiting `main`.
=> Move defer out of function body.

apps/task.go, apps/task_test.go
=> Don't sync TASK_KILLING services

consul/consul_test.go, consul/consul_test_server.go
The ACL token passing has been carried over from the forked project, but it had no tests.
I added an integration test, which proves the functionality works as expected.
=> ACL token passing integration test

consul/agents.go, consul/agents_test.go, consul/consul.go
Change `GetAnyAgent` to return `Agent` instead of `Client` to make API consistent.
=> Agents interface unification

README.md, consul/agents.go, consul/consul.go, consul/consul_test.go, consul/consul_test_server.go
If defined, the local consul agent is used to read list of services.
Otherwise, a random agent is picked, but only from the cache of agents
already syncing registrations.
This change prevents situations, where contacting a random agent in the
cluster fails, because it has no ACL-DC configured.
=> Local Agent used for service list reads (#276)

apps/app.go, apps/app_test.go
I've manually tested this end-to-end with Marathon, Consul, and this new binary. This patch addresses issue #230 
I'm able to manually compile this code using native `go run`. But I'm not able to run `make build`, etc. So maybe someone (@janisz) can test this?
=> Support Marathon 1.5 Network API

.travis.yml, Makefile, apps/app.go, consul/consul.go, consul/consul_stub.go, consul/consul_test.go, consul/consul_test_server.go, events/event_handler.go, events/event_handler_test.go, events/task_health_change.go, golangcilinter.yaml, marathon/marathon_test.go, metrics/metrics.go, metrics/system_metrics.go, service/service.go, service/service_test.go, sse/sse.go, sse/sse_handler.go, sync/sync.go, sync/sync_bench_test.go, sync/sync_test.go
Remove deprecated gometalinter
=> Upgrade linter to golangci-lint, bump Go to 1.12 for Travis

apps/app.go, apps/app_test.go
Adds a feature of port placeholders in Marathon labels that are resolved in consul tags when registering a service.
Placeholders format: `{port:<port name>}`, where `<port name>` should be a name of an existing port definitions. Such placeholder will be replaced by related port number when mapping Marathon labels into Consul tags.
=> Resolving port placeholders in Marathon labels

.goxc.json
Improvements:
* Resolve port placeholders `{port:name}` in Marathon labels (#292)
=> Release 1.5.1

.goxc.json, Makefile, config/config.go, consul/config.go, consul/consul.go, consul/consul_test.go, consul/consul_test_server.go
If some datacenter is marked in Consul cluster as "failed" Marathon-Consul still asks for services and fails after getting 500 in response. This PR adds option to configure single datacenter to ask for.
=> don't search in all DCs if configured
