allegro/marathon-consul

- consul/agents.go
- consul/agents_test.go
- consul/consul.go
- consul/consul_test.go
- consul/consul_test_server.go
- web_test.go
> GetAnyAgent returns random agent

- apps/app.go
- apps/app_test.go
- sync/sync.go
- web/event_handler.go
- web/event_handler_test.go
Added consul:true label check for apps in event handlers.
> Event handlers fix

- consul/agents.go
- consul/consul.go
- consul/consul_stub.go
- sync/sync.go
- sync/sync_bench_test.go
- sync/sync_test.go
> Sync optimization

- Makefile
This fixes the `make build` command.
> Make build fix

- web/event_handler.go
- web/event_handler_test.go
...and for other valid requests coming from Marathon. 
resolves #33
> Returning 200 OK for not handled events

- apps/task.go
- apps/task_test.go
- consul/consul.go
- consul/consul_stub.go
- consul/consul_test.go
- utils/apps.go
- utils/apps_test.go
> Service host to IPv4 resolving

- consul/agents.go
> Agents connection leak fix

- debian/marathon-consul.upstart
creates pidfile on application startup while using upstart
> Pidfile creation

- consul/consul_test.go
- consul/consul_test_server.go
- sync/sync_test.go
Some tests would randomly fail without reason, this PR should fix this.
> Fixes some flaky tests

- .travis.yml
- consul/consul_stub.go
- consul/consul_test.go
- service/service_test.go
- sync/sync_test.go
> Tests for separating service id from task id

- apps/app.go
- consul/consul.go
- events/events.go
- events/events_test.go
- utils/net.go
- web/event_handler.go
- web/event_handler_test.go
- web/health_handler.go
- web/web.go
`AppWrapper` and `eventHandler.New()` do not need to be public.
> Change structs to package private

- sync/sync.go
Just a minor log message update when doing sync to reflect changes in #125.
> Small sync log message update

- README.md
> Update README with Sentry.io configuration.

- .travis.yml
- Makefile
To update version just run `make version v=<version>` e.g., `make version v=1.2.0`.
> Make GitHub Release from Travis.

- README.md
- config/config.go
- config/config_test.go
- debian/config.json
- sentry/config.go
- sentry/init.go
Related to https://github.com/allegro/marathon-consul/issues/165
> Make sentry timeout configurable

- sync/sync.go
- sync/sync_test.go
When service is marked to be deregisterd during sync ask marathon for
tasks to recheck if this task was not started after sync procedure started.
Prevents deregistartion of tasks started after sync asked for all
marathon services. It also minimize call to marathon for a price
of not deregistering tasks that was killed during sync. This will
be handled by events or next sync.
> Recheck if service should be deregistered 

- events/event_handler.go
- events/event_handler_test.go
- events/web_events.go
- events/web_events_test.go
- web/web.go
- web/web_handler.go
- web/web_handler_test.go
I hope this change will make support of SSE and callbacks in the one binary simpler to deploy and clearer to implement.
> Partly Fixes #143 | Move event handler to events module

- consul/consul.go
- consul/consul_test.go
I have never programmed in Go. I am pretty sure this is the place for the change. Hopefully the syntax is correct for assigning to that variable.
> default HTTP(s) Path to / if empty

- main.go
- marathon/marathon.go
- sse/sse.go
- sse/sse_handler.go
> Exit on streamer start error.

- README.md
- config/config.go
- debian/config.json
- marathon/marathon.go
- marathon/marathon_stub.go
- marathon/streamer.go
- sse/config.go
- sse/sse_handler.go
- sync/error_marathon_stub_test.go
> Allow configuration of SSE recover retries.

- .travis.yml
- Makefile
Refs: https://blog.golang.org/go1.9
> Update go to 1.9

- .goxc.json
- .travis.yml
- Makefile
- apps/app.go
- consul/consul_test.go
Mirroring change: https://github.com/allegro/mesos-executor/pull/140/files
> Handle same port multiple service registration
